#define WIFI_SSID "SSID"
#define WIFI_PASSWORD "PASSWORD"
#define INFLUXDB_TOKEN "TOKEN"
#define INFLUXDB_URL "http://yourinfluxinstance:8086"
#define INFLUXDB_ORG "ORGANISATION"
#define INFLUXDB_BUCKET "BUCKET"
#define otaUser "xxx"
#define otaPass "xxx"
